Add app events v2
HedvigInsurance/hAnalytics pull request #22
Opened 2022-05-20 10:00 UTC by sonnyandersson1

Added 
- card_click_cross_sell
- open_chat_click

Don't know if all inputs are correctly named. Please double check that.

The most important thing is to have the typeOfContracts aligned througout signed+offer+card click so we easily can build funnels in looker with one identifyer (typeOfContracts in this case)

2022-05-31 12:45 UTC, oscarnylander commented on definitions/events/app/chat/openChatClick.yml
> +name: open_chat_click
It should be possible to derive this event from `screen_view { CHAT }` and simply taking the previous `screen_view`-event, right? @sonnyandersson1

2022-05-31 12:45 UTC, oscarnylander commented on definitions/events/app/onboarding/cardClickCrossSell.yml
> +  - name: initiated_from
What would this parameter say? 🤔

2022-05-31 12:45 UTC, oscarnylander commented on definitions/events/app/onboarding/cardClickCrossSell.yml
> +  - name: type_of_contracts
I think a cross-sell can only have one `typeOfContract`-parameter.

2022-05-31 13:15 UTC, sampettersson requested changes

2022-05-31 13:15 UTC, sampettersson commented on definitions/events/app/chat/openChatClick.yml
> +    type: ScreenName
```suggestion
    type: AppScreen
```

2022-05-31 13:15 UTC, sampettersson commented on definitions/events/app/chat/openChatClick.yml
> +    argument: screenName
```suggestion
    argument: screen
```

2022-05-31 13:15 UTC, sampettersson commented on definitions/events/app/onboarding/cardClickCrossSell.yml
> +  - name: type_of_contracts
Yeah, lets rename this to `id` and we will for now pass typeOfContract.

2022-05-31 13:15 UTC, sampettersson commented on definitions/events/app/chat/openChatClick.yml
> +name: open_chat_click
@oscarnylander its quite hard to do that analysis with just pure SQL and not a bunch of data engineering so this was the suggested way to do it.

2022-05-31 13:35 UTC, oscarnylander commented on definitions/events/app/chat/openChatClick.yml
> +name: open_chat_click
Fair enough. I think it might get kind of tricky to know whether every call site has been implemented using this event definition though 🤔 perhaps an alternative could be a per-call site event definition could be more appropriate - that way we could easily determine whether the event is implemented or not.

2022-06-01 07:44 UTC, sampettersson commented on definitions/events/app/chat/openChatClick.yml
> +name: open_chat_click
@oscarnylander yeah, that was what i was thinking initially also, so lets maybe go with that for now, its what we do elsewhere anyhow.

2022-06-01 07:54 UTC, merged